project:
  type: website

website:
  title: "Manim"
  navbar:
    left:
      - href: manim.qmd
        text: Slides

format:
  revealjs:
    theme: default
    css: styles.css
    slide-number: true
    scrollable: true
    code-annotations: select
    code-overflow: wrap
revealjs-plugins:
  - codefrag
